<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <Title>PC Gaming Mod App</Title>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/ff2009/pc-gaming-mod-platform</RepositoryUrl>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Remove="Assets\Images\game-control.png" />
    <AvaloniaResource Remove="Assets\Images\game-controller.png" />
    <AvaloniaResource Remove="Assets\Images\game.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.DataGrid" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Update="Assets\Images\StoreIcons\ea.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\Images\StoreIcons\epic.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\Images\StoreIcons\gog.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\Images\StoreIcons\steam.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\Images\StoreIcons\ubisoft.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </AvaloniaResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\AddOnsPageView.axaml.cs">
      <DependentUpon>AddOnsPageView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\AboutPageView.axaml.cs">
      <DependentUpon>AboutPageView.axaml</DependentUpon>
    </Compile>
      <Compile Update="Views\GameMenuView.axaml.cs">
      <DependentUpon>GameListMenuView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\SystemPageView.axaml.cs">
      <DependentUpon>SystemPageView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\DeveloperSettingsPageView.axaml.cs">
      <DependentUpon>DeveloperSettingsPageView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\HomePageView.axaml.cs">
      <DependentUpon>HomePageView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\BasePageView.axaml.cs">
      <DependentUpon>BasePageView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\GameSettingsPageView.axaml.cs">
      <DependentUpon>GameSettingsPageView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\Images\game-control.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Images\game-controller.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Images\game.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PCGamingModApp.Core\PCGamingModApp.Core.csproj" />
  </ItemGroup>
</Project>
