<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Castle.Core"/>
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\PCGamingModApp.Core\PCGamingModApp.Core.csproj"/>
      <ProjectReference Include="..\..\src\PCGamingModApp.Data\PCGamingModApp.Data.csproj" />
        <ProjectReference Include="..\PCGamingModApp.Tests.Utilities\PCGamingModApp.Tests.Utilities.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="CommunityToolkit.Mvvm">
            <HintPath>..\..\..\..\.nuget\packages\communitytoolkit.mvvm\8.4.0\lib\net8.0\CommunityToolkit.Mvvm.dll</HintPath>
        </Reference>
        <Reference Include="Moq">
            <HintPath>..\..\..\..\.nuget\packages\moq\4.20.72\lib\net6.0\Moq.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Helpers\"/>
    </ItemGroup>

</Project>
