<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="CommunityToolkit.Mvvm"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
        <PackageReference Include="System.Drawing.Common" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Models\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\PCGamingModApp.Data\PCGamingModApp.Data.csproj" />
    </ItemGroup>

</Project>
